### ISSUE TITLE
Is it possible to load surfer grid as surface and not just image of contoured data?

### ISSUE THREAD

**Issue by hal98x** [3ptscience/steno3d-surfer#4]
The most recent project I am working on I have created several surfer grid files that are undulating surfaces. I would like to load these into steno3D and display as surfaces. I ask because so far steno3d-surfer has only been used to load a flat surface and apply a color scale to gridded data. I now need a surface from the surfer grid file.

I bought the professional package so I am hoping I can get some support for my two issues on this forum ASAP.

**Comment by fwkoch** [comment]
Hi @hal98x - supporting undulating surfaces should be supported in the current version. `parse` (see [the call signature](https://github.com/3ptscience/steno3d-surfer/blob/v0.0.2/steno3d_surfer/parser.py#L22)) allows a keyword argument `as_topo`, which if True, adds the [data as topography](https://github.com/3ptscience/steno3d-surfer/blob/v0.0.2/steno3d_surfer/parser.py#L86) and if False, only adds the data as flat color.
```
import steno3d, steno3d_surfer
(proj,) = steno3d.parsers.grd('my_file.grd').parse(as_topo=True)
```
Note - this will still add the Z-value color as well. To remove this dataset (but keep the undulating surface) you can do:
```
proj.resources[0].data = []
```

If your surfaces are still not loading to Steno3D as you expect, can you follow up with more details about your grid file (ie surfer version 6 or 7, binary or ascii, data ranges, etc)? Thanks!

**Comment by hal98x** [comment]
Thanks this worked I am just getting back into steno3d after a busy fall and winter. 

When I display in chrome I see these weird black lines that converge to a point offscreen. 

I am on Windows 7 running anaconda 2.7.12 and Jupyter Notebook. I was running Jupyter in IE but visualizing my model in Chrome. I loaded two surfer grid files as surfaces with the code below. 

import numpy as np
import steno3d
import steno3d_surfer

proj = steno3d.Project(
    title='Schmitz 44-30 ERT and EM Project',
    public=False
)


parser = steno3d.parsers.grd('Data_for_lines_stations.grd')
parser.parse(proj, as_topo=True)



proj.resources[-1].title = 'Topography'

m = proj.resources[-1].mesh

parser = steno3d.parsers.grd('Data_for_lines_stations_subsf.grd')
parser.parse(proj, as_topo=True)

proj.resources[-1].title = 'Bottom of Saturated Zone'

m = proj.resources[-1].mesh

steno3d.login()
proj.upload()

[Data_for_lines_stations_subsf.zip](https://github.com/3ptscience/steno3dpy/files/912103/Data_for_lines_stations_subsf.zip)

I see a bunch of black lines converging to a point offscreen. (See attached screen shot)

![steno_error](https://cloud.githubusercontent.com/assets/5559354/24892524/25ed7610-1e32-11e7-8db4-98df30d8b4df.jpg)


Sincerely,


Michael Wallace

**Comment by fwkoch** [comment]
I'm glad the topo worked smoothly. I'm closing this issue in favor of the black lines issue you made here: https://github.com/3ptscience/steno3dpy/issues/125
